# Generated by Django 5.0.3 on 2024-03-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("gender", models.CharField(max_length=10)),
                ("telephone", models.CharField(max_length=11)),
                ("address", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("bloodgroup", models.CharField(max_length=5)),
            ],
        ),
    ]
