# Generated by Django 5.0.3 on 2024-03-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctorname", models.CharField(max_length=50)),
                ("patientname", models.CharField(max_length=50)),
                ("doctoremail", models.EmailField(max_length=50)),
                ("patientemail", models.EmailField(max_length=50)),
                ("appointmentDate", models.DateField()),
                ("appointmentTime", models.TimeField()),
                ("symptoms", models.CharField(max_length=100)),
                ("prescription", models.CharField(max_length=200)),
                ("status", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("gender", models.CharField(max_length=10)),
                ("telephone", models.CharField(max_length=11)),
                ("address", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("bloodgroup", models.CharField(max_length=5)),
                ("specialisation", models.CharField(max_length=50)),
            ],
        ),
    ]
